---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    app: kafka
spec:
  ports:
  - name: "9092"
    port: 9092
    targetPort: 9092
    nodePort: 30004
  selector:
    app: kafka
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: ubuntu/kafka:edge
        env:
          - name: KAFKA_NODE_ID
            value: "1"
          - name: KAFKA_PROCESS_ROLES
            value: "controller,broker"
          - name: KAFKA_LISTENERS
            value: "PLAINTEXT://:9092,CONTROLLER://:9093"
          - name: KAFKA_ADVERTISED_LISTENERS
            value: "PLAINTEXT://kafka-service:9092"
          - name: KAFKA_CONTROLLER_QUORUM_VOTERS
            value: "1@kafka-service:9093"
          - name: KAFKA_LOG_DIRS
            value: "/var/lib/kafka/data"
        args: ["/etc/kafka/server.properties"]
        ports:
        - containerPort: 9092
          name: kafka
          protocol: TCP
        - containerPort: 9093
          name: controller
          protocol: TCP
